---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1

server:
  port: 8000

eureka:
  instance:
    hostname: peer1

  client:
    register-with-eureka: false #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false  #为true时，可以启动，但报异常：Cannot execute request on any known
    service-url:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2

server:
  port: 8001

eureka:
  instance:
    hostname: peer2

  client:
    register-with-eureka: false #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false  #为true时，可以启动，但报异常：Cannot execute request on any known
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3

server:
  port: 8002

eureka:
  instance:
    hostname: peer3

  client:
    register-with-eureka: false #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false  #为true时，可以启动，但报异常：Cannot execute request on any known
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/

#  server:
#    enable-self-preservation: false  #自我保护模式关闭
