spring:
  application:
    name: spring-cloud-consumer

server:
  port: 9002


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/   #指向注册中心地址

feign:
  hystrix:
    enabled: true  #开启降级操作
