spring:
  application:
    name: spring-cloud-config-client
  rabbitmq:
    host: 106.13.162.44
    username: admin
    password: admin-rabbitmq
    port: 5672

server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        #使用项目路径 +/actuator/bus-refresh 来刷新标记@RefreshScope注解的配置
        include: "*"
  endpoint:
    env:
      #启用端点 env
      enabled: true
