server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TodayIsSunShine/spring-cloud-study   #配置git仓库的地址
          search-paths: neo-config         #git仓库相对路径下的地址,可以配置多个,用逗号分隔
          #默认加密方式PBEWithMD5AndDES,可以更改为PBEWithMD5AndTripleDES
          username: ENC(TgsbUwTrTd0nM6es3ZlhwZ/O0//FhyHf)         #git仓库的账号
          password: ENC(30biMzIQPYWtu5/G1m7r6dkOZu2Gi2F+)         #git仓库的密码
          force-pull: true                  #yml配置文件时,加上该配置获取配置文件最新代码,否则返回[]
  rabbitmq:
    host: 106.13.162.44
    port: 5672   #15672是后台管理端口,5672是客户端端口
    username: admin
    password: admin-rabbitmq


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    appname: spring-cloud-config-server
    prefer-ip-address: true  #在注册中心显示ip地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true #启用端点env
jasypt:
  encryptor:
    #加密所需要的salt
    password: yoursalt
